### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by ipa-vsp** [LernFabrik/kuka_iiwa7_ros2#11]
- [ ] Integrate with the mobile planner. 
- [ ] More PLC control. 
- [ ] ROS PC headless going to sleep mode automatically (Fix).
- [ ] New KUKA error on 15.02.2023, CK COMMUNICATION error. Require further analysis and fixing.
